$MAIN_MONITOR = DP-1
$SECOND_MONITOR = HDMI-A-1
$WALLPAPER_MAIN = $HOME/wallpapers/.current_main
$WALLPAPER_SECOND = $HOME/wallpapers/.current_second

wallpaper {
    monitor = $MAIN_MONITOR
    path = $WALLPAPER_MAIN
}
wallpaper {
    monitor = $SECOND_MONITOR
    path = $WALLPAPER_SECOND
}
splash = false
