# Set default monitors for workspaces
workspace = 1, monitor:$MAIN_MONITOR, default:true
workspace = 2, monitor:$SECOND_MONITOR, default:true
workspace = 3, monitor:$SECOND_MONITOR
workspace = 4, monitor:$MAIN_MONITOR
workspace = 5, monitor:$MAIN_MONITOR
