# Brightness controls
bindel = , XF86MonBrightnessUp, exec, brightnessctl set 5%+; $SCRIPTS_DIR/current-brightness.sh | xargs $OSD-client --brightness
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-; $SCRIPTS_DIR/current-brightness.sh | xargs $OSD-client --brightness
