$MAIN_MONITOR = DP-1
$SECOND_MONITOR = HDMI-A-1
$WALLPAPER_2K = $HOME/wallpapers/2k/.current
$WALLPAPER_HD = $HOME/wallpapers/hd/.current

wallpaper {
    monitor = $MAIN_MONITOR
    path = $WALLPAPER_2K
}
wallpaper {
    monitor = $SECOND_MONITOR
    path = $WALLPAPER_HD
}
splash = false

